### ISSUE TITLE
Add podman to the prototype architecture (Drawio)

### ISSUE THREAD

**Issue by amir-varasteh** [margo/app-observability-wg#11]

**Comment by phil-abb** [comment]
@amir-varasteh I'm assuming you're just wanting me to update the diagram to show both the docker and podman standalone deployments instead of just the single standalone deployment. Correct?

**Comment by amir-varasteh** [comment]
@phil-abb Yes, please. Because I do not have access to the source file.

**Comment by phil-abb** [comment]
@amir-varasteh  updated
